query InvoiceObjectsOpen {
	invoiceObjectsOpen {
		id
		valueDollar
		valueReal
		dollarQuote
		percentProfit
		percentProfit
		percentFess
		percentAffiliated
		status
		paymenbeginDate
		expirationDate
	}
}
