mutation {
	createUserResolver(
		data: {
			email: "testaaas25a@test.com"
			password: "Teste25@"
			name: "Jaison Manders"
			numberTelephone: "5566999891"
		}
	) {
		field
		message
	}
}

mutation {
	createUserResolver(
		data: {
			email: "admsss5a@test.com"
			password: "Teste25@"
			name: "Jaison Manders"
			affiliate: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsIkVudW0iOiIiLCJpYXQiOjE2NTY4MjA1Njd9.CgZwXw_V7eGDsQzsM1XJU8zNsAfHnPK61NVhUPFWvpyGI"
		}
	) {
		field
		message
	}
}
mutation {
	loginAuthUser(
		data: { email: "testaaas25a@test.com", password: "Teste25@" }
	) {
		field
		message
	}
}

mutation {
	updateAuthPassword(
		data: { oldPassword: "Teste25@", password: "Teste24@" }
	) {
		field
		message
	}
}

mutation {
	userWalletUpdate(data: { wallet: "4Mvf7CaRLirAmpnjz1ZH3bWNkQ" }) {
		field
		message
	}
}

mutation {
	updateNumberTelephone(data: { numberTelephone: "569120993" }) {
		field
		message
	}
}

query {
	userInfoDocument {
		email
		name
		wallet
		valuePrice
		document
		numberTelephone
	}
}

query {
	userAllMoney {
		balance
		profitCycle
		profitFuture
	}
}

mutation {
	logout
}

mutation {
	resolverForgetPassword(data: { email: "est25ac@test.com" }) {
		field
		message
	}
}

mutation {
	newPassword(data: { token: "", password: "" }) {
		field
		message
	}
}

mutation {
	userValidAccount(data: { token: "*******" }) {
		field
		message
	}
}

mutation {
	userBaseInfoUpdate(data: { name: "", numberTelephone: "" }) {
		field
		message
	}
}

query {
	userLinkAffiliate {
		token
	}
}
